dist: xenial

language: python
python:
  - 3.7
  - 3.8
  - 3.9

cache:
  pip: true
  directories:
    - ${VIRTUAL_ENV}

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - make doctor

install:
  - make install

script:
  - make test-repeat
  - make check
  - make notebooks
  - make mkdocs

after_success:
  - pip install coveralls "coverage<5"
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: never
